name: Aerial Point Productions TEST
favicon: null
layout_spectrum: 0.30476477881893516
typography_spectrum: 0.37836854881606996
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.48153369943611324
  lightness: 0.4209988731890917
  saturation: 0.4252499716822058
  rhythmicContrast: 0.9911496578715742
purpose: []
