favicon: null
name: Aerial Point Productions TEST
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.5
  brandStrength: 0
  rhythmicContrast: 0.5
  brandColors:
    - '#211f20'
    - '#ffffff'
    - '#6e6f71'
    - '#dadbdd'
    - '#515254'
  lightness: 0.5
typography_spectrum: 0.1260454
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.4235364
analytics:
  twitter: null
  google: null
  facebook: null
