analytics: {}
color:
  brandColors:
    - '#211f20'
    - '#ffffff'
    - '#6e6f71'
    - '#dadbdd'
    - '#515254'
  brandStrength: 0.5
  lightness: 0.4209988731890917
  rhythmicContrast: 0.9911496578715742
  saturation: 0.4252499716822058
cta: {}
layout_spectrum: 0.391233
name: Aerial Point Productions TEST
opengraph: {}
purpose: []
typography_spectrum: 0.40968
