name: Aerial Point Productions TEST
favicon: null
layout_spectrum: 1
typography_spectrum: 0.40968
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#211f20'
    - '#ffffff'
    - '#6e6f71'
    - '#dadbdd'
    - '#515254'
  brandStrength: 1
  lightness: 0.4209988731890917
  saturation: 0.4252499716822058
  rhythmicContrast: 1
purpose: []
