name: Aerial Point Productions TEST
favicon: null
layout_spectrum: 0
typography_spectrum: 0.40968
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#211f20'
    - '#ffffff'
    - '#6e6f71'
    - '#dadbdd'
    - '#515254'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
